; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Haiku"
#define MyAppVersion "1.0"
#define MyAppPublisher "Sajidur Rahman"
#define MyAppURL "https://github.com/SajidurRahmanMahedi/Haiku"
#define MyAppExeName "haiku.exe"
#define MyFileTypeId   "YolishFile"
#define MyFileTypeDesc "Yolish Source File"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6D03CD1D-7BDE-4CE5-8295-3471CCFD41D1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
UsedUserAreasWarning=no
OutputDir=Output
OutputBaseFilename=haiku
SetupIconFile=icon.ico
SolidCompression=yes
WizardStyle=modern dynamic
ChangesEnvironment=yes
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "file.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent unchecked

[Registry]

; --- PATH ---
; Admin install → system-wide PATH (HKLM)
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; \
    Check: IsAdminInstallMode and NeedsAddPath(ExpandConstant('{app}')); \
    Flags: preservestringtype

; Non-admin install → current-user PATH (HKCU)
Root: HKCU; Subkey: "Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; \
    Check: (not IsAdminInstallMode) and NeedsAddPath(ExpandConstant('{app}')); \
    Flags: preservestringtype

; --- .hku file association ---
; Extension key
Root: HKLM; Subkey: "SOFTWARE\Classes\.hku"; ValueType: string; ValueName: ""; ValueData: "{#MyFileTypeId}"; Flags: uninsdeletekey; Check: IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\.hku"; ValueType: string; ValueName: ""; ValueData: "{#MyFileTypeId}"; Flags: uninsdeletekey; Check: not IsAdminInstallMode

; ProgID
Root: HKLM; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}"; ValueType: string; ValueName: ""; ValueData: "{#MyFileTypeDesc}"; Flags: uninsdeletekey; Check: IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}"; ValueType: string; ValueName: ""; ValueData: "{#MyFileTypeDesc}"; Flags: uninsdeletekey; Check: not IsAdminInstallMode

; Default icon
Root: HKLM; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\file.ico,0"; Flags: uninsdeletekey; Check: IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\file.ico,0"; Flags: uninsdeletekey; Check: not IsAdminInstallMode

; shell\open
Root: HKLM; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey; Check: IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey; Check: not IsAdminInstallMode

; shell\run
Root: HKLM; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\run"; ValueType: string; ValueName: ""; ValueData: "Run with Yolish"; Flags: uninsdeletekey; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\run\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey; Check: IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\run"; ValueType: string; ValueName: ""; ValueData: "Run with Yolish"; Flags: uninsdeletekey; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\run\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey; Check: not IsAdminInstallMode

; shell\compile
Root: HKLM; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\compile"; ValueType: string; ValueName: ""; ValueData: "Compile with Yolish"; Flags: uninsdeletekey; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\compile\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" -c ""%1"""; Flags: uninsdeletekey; Check: IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\compile"; ValueType: string; ValueName: ""; ValueData: "Compile with Yolish"; Flags: uninsdeletekey; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\{#MyFileTypeId}\shell\compile\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" -c ""%1"""; Flags: uninsdeletekey; Check: not IsAdminInstallMode

[Code]
function NeedsAddPath(Dir: string): Boolean;
var
  EnvPath: string;
begin
  if IsAdminInstallMode then
  begin
    if not RegQueryStringValue(HKLM,
        'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
        'Path', EnvPath) then
      EnvPath := '';
  end
  else
  begin
    if not RegQueryStringValue(HKCU, 'Environment', 'Path', EnvPath) then
      EnvPath := '';
  end;
  Result := Pos(Lowercase(Dir), Lowercase(EnvPath)) = 0;
end;


